internHub/hub/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^student/$', views.index, name='index'),
    url(r'^student/register/$', views.reg_student, name='reg_student'),
    url(r'^student/login/$', views.login_stu, name='login_stu'),
    url(r'^student/registered/$', views.register_student, name='register_student'),
    url(r'^student/redirect/$', views.login_student, name='login_student'),
    url(r'^student/job/(?P<job_id>[0-9]+)/$', views.job_view, name='job_view'),
    url(r'^student/job/(?P<job_id>[0-9]+)/apply/$', views.model_form_upload, name='model_form_upload'),
    url(r'^student/skill/(?P<skill>[\w-]+)/$', views.skill_filter, name='skill_filter'),
    url(r'^student/applications/$', views.student_applications, name='student_applications'),
    url(r'^student/applications/(?P<job_id>[0-9]+)/$', views.job_desc_view, name='job_desc_view'),
    url(r'^student/logout/$', views.logout_stu, name='student_logout'),
    url(r'^employer/$', views.index_emp, name='index_emp'),
    url(r'^employer/register/$', views.reg_employer, name='reg_employer'),
    url(r'^employer/registered/$', views.register_employer, name='register_employer'),
    url(r'^employer/login/$', views.login_emp, name='login_emp'),
    url(r'^employer/logout/$', views.logout_emp, name='employer_logout'),
    url(r'^employer/redirect/$', views.login_employer, name='login_employer'),
    url(r'^employer/skill/(?P<skill>[\w-]+)/$', views.skill_filter_emp, name='skill_filter_emp'),
    url(r'^employer/job/(?P<job_id>[0-9]+)/$', views.job_view_emp, name='job_view_emp'),
    url(r'^employer/job/(?P<job_id>[0-9]+)/applications/$', views.job_applications, name='job_applications'),
    url(r'^employer/new_job/$', views.create_job, name='create_job'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

internHub/internHub/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from material.frontend import urls as frontend_urls
from django.conf import settings
from django.conf.urls.static import static

from hub import views

urlpatterns = [
    url(r'^hub/', include('hub.urls')),
    url(r'^admin/logout/$', views.redirect_home, name='redirect_home'),
    url(r'', include(frontend_urls)),
    url(r'^$', views.redirect_home, name='redirect_home'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

internHub/hub/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.auth.models import User

# Create your models here.
class Company(models.Model):
    company_name = models.CharField(max_length=50)
    
    #@python_2_unicode_compatible
    def __str__(self):
        return self.company_name
    
class Employer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=None)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, default=None)
    
    #@python_2_unicode_compatible
    def __str__(self):
        return self.company.company_name

class Job(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    SKILL_CHOICES = (
        ('J', 'Junior'),
        ('I', 'Intermediate'),
        ('S', 'Senior'),
    )
    skill = models.CharField(max_length=1, choices=SKILL_CHOICES)
    employer = models.ForeignKey(Employer, on_delete=models.CASCADE, default=None)
    deadline = models.DateField(default=datetime.date.today)
	
    #@python_2_unicode_compatible
    def __str__(self):
        return self.title + " - " + self.employer.company.company_name

    
class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=None)
    program = models.CharField(max_length=150, null=True)
    year_of_study = models.IntegerField(null=True)
    year_of_graduation = models.IntegerField(null=True)

class School(models.Model):
    name = models.CharField(max_length=100)

class Documents(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE, default=None)
    resume = models.FileField(upload_to='resumes/')
    cover_letter = models.FileField(upload_to='cover_letters/', blank=True, null=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    
    #@python_2_unicode_compatible
    def __str__(self):
        return self.job.title + " - " + self.user.email

internHub/hub/forms.py
from django import forms

from .models import Documents, Job


class DocumentForm(forms.ModelForm):
    class Meta:
        model = Documents
        fields = ('resume', 'cover_letter' )

        
class CreateJobForm(forms.ModelForm): 
    class Meta:
        model = Job
        fields = ('title', 'description', 'skill', 'deadline')
        

internHub/hub/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout, get_user
from django.conf import settings
from django.core.files.storage import FileSystemStorage

# Create your views here.
from .models import Job
from .models import Employer
from .models import Company
from .models import Student 
from .models import Documents

from .forms import DocumentForm, CreateJobForm

def home(request):
    return render(request, 'hub/home.html')

def redirect_home(request):
    logout(request)
    # Redirect to a home page here.
    return redirect('home')

def reg_employer(request):
    job_list = Job.objects.all().order_by('deadline')
    context = {
        'mesage': "Welcome new Employer",
    }
    return render(request, 'hub/register_employer.html', context)

def reg_student(request):
    job_list = Job.objects.all().order_by('deadline')
    context = {
        'mesage': "Welcome",
    }
    return render(request, 'hub/register_student.html', context)

def index(request):
    job_list = Job.objects.all().order_by('deadline')
    context = {
        'job_list': job_list,
    }
    return render(request, 'hub/index.html', context)

def index_emp(request):
    employer = Employer.objects.all().filter(user=request.user)
    job_list = Job.objects.all().filter(employer=employer)
    context = {
        'job_list': job_list,
    }
    return render(request, 'hub/employer_home.html', context)
    
def job_view(request, job_id):
    job = Job.objects.get(id=job_id)
    context = {
        'job': job,
    }
    return render(request, 'hub/job.html', context)

def job_view_emp(request, job_id):
    job = Job.objects.get(id=job_id)
    context = {
        'job': job,
    }
    return render(request, 'hub/job_emp.html', context)

def job_applications(request, job_id):
    job = Job.objects.get(id=job_id)
    applications = Documents.objects.filter(job=job)
    context = {
        'applications': applications,
    }
    return render(request, 'hub/job_applications.html', context)
    
def job_desc_view(request, job_id):
    job = Job.objects.get(id=job_id)
    context = {
        'job': job,
    }
    return render(request, 'hub/job_desc.html', context)

def skill_filter(request, skill):
    job_list = Job.objects.filter(skill=skill)
    context = {
        'job_list': job_list,
    }
    return render(request, 'hub/index.html', context)
    
def skill_filter_emp(request, skill):
    employer = Employer.objects.all().filter(user=request.user)
    job_list = Job.objects.all().filter(skill=skill, employer=employer)
    context = {
        'job_list': job_list,
    }
    return render(request, 'hub/employer_home.html', context)

def student_applications(request):
    job_list = Documents.objects.filter(user=request.user)
    context = {
        'job_list': job_list,
    }
    return render(request, 'hub/student_applications.html', context)

def register_employer(request):
    try:
        username = request.POST['username']
        password = request.POST['password']
        email = request.POST['email']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        company_name = request.POST['company']
    except:
        return HttpResponse("Missing a required field")
    else:
        new_user = User.objects.create_user(username=username, password=password, email=email, first_name=first_name, last_name=last_name, is_staff=False)
        new_user.save()
        try:
            company = Company.objects.get(company_name=company_name)
        except:
            company = Company(company_name=company_name)
            company.save()
        new_employer = Employer(user=new_user, company=company)
        new_employer.save()
        
        job_list = Job.objects.all().order_by('deadline')
        context = {
            'job_list': job_list,
        }
        return render(request, 'hub/employer_login.html', context)
        
def register_student(request):
    try:
        username = request.POST['username']
        password = request.POST['password']
        email = request.POST['email']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        school = request.POST['school']
    except:
        return HttpResponse("Missing a required field")
    else:
        new_user = User.objects.create_user(username=username, password=password, email=email, first_name=first_name, last_name=last_name, is_staff=False)
        new_user.save()
        new_student = Student(user=new_user)
        new_student.save()

        job_list = Job.objects.all().order_by('deadline')
        context = {
            'job_list': job_list,
        }
        return render(request, 'hub/student_login.html', context)

def model_form_upload(request, job_id):
    job = Job.objects.get(id=job_id)
    user = request.user
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)

        if form.is_valid():
            application = form.save(commit=False)  
            application.job = job
            application.user = user
            application.save()
            form.save_m2m()
            return redirect('job_view', job_id)
    else:
        form = DocumentForm()
    return render(request, 'hub/apply.html', {
        'form': form,
        'job': job,
        'user': user,
    })
    
def create_job(request):
    employer = Employer.objects.get(user=request.user);
    if request.method == 'POST':
        form = CreateJobForm(request.POST, request.FILES)

        if form.is_valid():
            job = form.save(commit=False)  
            job.employer = employer
            job.save()
            form.save_m2m()
            return redirect('index_emp')
    else:
        form = CreateJobForm()
    return render(request, 'hub/new_job.html', {
        'form': form,
        'user': request.user,
    })

def login_student(request):
    username = request.POST.get("username", "")
    password = request.POST.get("password", "")
    user = authenticate(username=username, password=password)
    if user is not None:
        login(request, user)

        job_list = Job.objects.all().order_by('deadline')
        context = {
            'job_list': job_list,
        }
        return render(request, 'hub/index.html', context)
    else:
        return HttpResponse("Log in failed. Invalid credentials")
        
def login_stu(request):
    context = {
        'mesage': "Welcome",
    }
    return render(request, 'hub/student_login.html', context)

def login_emp(request):
    context = {
        'mesage': "Welcome",
    }
    return render(request, 'hub/employer_login.html', context)

def login_employer(request):
    username = request.POST.get("username", "")
    password = request.POST.get("password", "")
    user = authenticate(username=username, password=password)
    if user is not None:
        login(request, user)

        employer = Employer.objects.all().filter(user=request.user)
        job_list = Job.objects.all().filter(employer=employer)
        context = {
            'job_list': job_list,
        }
        return render(request, 'hub/employer_home.html', context)
    else:
        return HttpResponse("Log in failed. Invalid credentials")

def logout_stu(request):
    logout(request)
    # Redirect to a home page here.
    return redirect('home')
    
def logout_emp(request):
    logout(request)
    # Redirect to a home page here.
    return redirect('home')

def logout_view(request):
    logout(request)

internHub/hub/templates/hub/apply.html
{% extends 'hub/base.html' %}

{% block title %}{{ job.title }}{% endblock %}
{% block other_styles %}
<!-- Page styles -->  
<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">


<style>
.full-width {
  width: 100%;
}
</style> 
{% endblock %}

{% block middle_content %}
  <div style="padding: 80px 56px" class="content mdl-card mdl-shadow--2dp full-width">
    <h1>{{ job.title }}</h1>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input type="file" style="color:transparent;" onchange="this.style.color = 'black';" name="resume" required id="id_resume">
        <input class="mdl-textfield__input" placeholder="Resume" type="text" id="uploadFile1" readonly/>
        <input type="file" style="color:transparent;" onchange="this.style.color = 'black';" name="cover_letter" id="id_cover_letter">
        <input class="mdl-textfield__input" placeholder="Cover Letter" type="text" id="uploadFile2" readonly/>  
      </div>
      <br>
      <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" type="submit">
      Submit
      </button>
    </form>
  </div>
{% endblock %}

{% block scripts %}
  <script>
    document.getElementById("id_resume").onchange = function () {
    document.getElementById("uploadFile1").value = this.files[0].name;
    };
    document.getElementById("id_cover_letter").onchange = function () {
    document.getElementById("uploadFile2").value = this.files[0].name;
    };
  </script>
{% endblock %}

internHub/hub/templates/hub/employer_home.html
{% extends 'hub/base_employer.html' %}

{% block title %}Employer{% endblock %}

{% block other_styles %}
  <link rel="stylesheet" href="/hub/static/css/style.css">

  <style>
  .full-width {
    width: 100%;
  }
  </style> 
{% endblock %}

{% block left_content %}
<a style="float: right;"class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" onclick="window.location.href='/hub/employer/new_job/'">
      New Job
</a>
{% endblock %}

{% block middle_content %}
  <div id="mdl-table">
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable is-upgraded is-focused">
      <label class="mdl-button mdl-js-button mdl-button--icon" for="sample6">
              <i class= "material-icons">search</i>
      </label>
      <div class="mdl-textfield__expandable-holder full-width">
              <input class="mdl-textfield__input search full-width" type="text" id="sample6">
              <label class="mdl-textfield__label" for="sample-expandable">Expandable Input</label>
      </div>
    </div>
    <table id='mdl-table' class="mdl-data-table mdl-js-data-table mdl-data-table mdl-shadow--2dp full-width">
      <thead>
        <tr>
          <th class="mdl-data-table__cell--non-numeric" data-sort="jobtitle">Job Title</th>
          <th class="mdl-data-table__cell--non-numeric" data-sort="employer">Employer</th>
          <th class="mdl-data-table__cell--non-numeric">Skill Level</th>
          <th class="mdl-data-table__cell sort" data-sort="deadline">Deadline</th>
        </tr>
      </thead>
      <tbody class="list">
        {% for job in job_list %}
          <tr>
            <td class="mdl-data-table__cell--non-numeric jobtitle"><a href="/hub/employer/job/{{ job.id }}/">{{ job.title }}</td>
            <td class="mdl-data-table__cell--non-numeric employer">{{ job.employer.company.company_name }}</td>
            <td class="mdl-data-table__cell--non-numeric">{{ job.get_skill_display }}</td>
            <td class="mdl-data-table__cell deadline">{{ job.deadline }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>



{% endblock %}

{% block right_content %}
  
             <!-- Right aligned menu below button -->
  Skill Level
  <button id="demo-menu-lower-right"
          class="mdl-button mdl-js-button mdl-button--icon"> 
    <i class="material-icons">more_vert</i>
  </button>

  <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect"
        for="demo-menu-lower-right">
    <a style="text-decoration: none" href="/hub/employer/skill/J"><li class="mdl-menu__item">Junior</li></a>
    <a style="text-decoration: none" href="/hub/employer/skill/I"><li class="mdl-menu__item">Intermediate</li></a>
    <!--<li disabled class="mdl-menu__item">Disabled Action</li> -->
    <a style="text-decoration: none" href="/hub/employer/skill/S"><li class="mdl-menu__item">Senior</li></a>
  </ul>


{% endblock %}

{% block external_scripts %}
  <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0-alpha1/jquery.min.js'></script>
  <script src='https://s3-us-west-2.amazonaws.com/s.cdpn.io/4579/list.min.js'></script>
  <script src="/hub/static/js/index.js"></script>
{% endblock %}

internHub/hub/templates/hub/index.html
{% extends 'hub/base.html' %}

{% block title %}Student{% endblock %}

{% block other_styles %}
  <link rel="stylesheet" href="/hub/static/css/style.css">

  <style>
  .full-width {
    width: 100%;
  }
  </style> 
{% endblock %}

{% block middle_content %}
  <div id="mdl-table">
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable is-upgraded is-focused">
      <label class="mdl-button mdl-js-button mdl-button--icon" for="sample6">
              <i class="material-icons">search</i>
      </label>
      <div class="mdl-textfield__expandable-holder full-width">
              <input class="mdl-textfield__input search full-width" type="text" id="sample6">
              <label class="mdl-textfield__label" for="sample-expandable">Expandable Input</label>
      </div>
    </div>
    <table id='mdl-table' class="mdl-data-table mdl-js-data-table mdl-data-table mdl-shadow--2dp full-width">
      <thead>
        <tr>
          <th class="mdl-data-table__cell--non-numeric" data-sort="jobtitle">Job Title</th>
          <th class="mdl-data-table__cell--non-numeric" data-sort="employer">Employer</th>
          <th class="mdl-data-table__cell--non-numeric">Skill Level</th>
          <th class="mdl-data-table__cell sort" data-sort="deadline">Deadline</th>
        </tr>
      </thead>
      <tbody class="list">
        {% for job in job_list %}
          <tr>
            <td class="mdl-data-table__cell--non-numeric jobtitle"><a href="/hub/student/job/{{ job.id }}/">{{ job.title }}</td>
            <td class="mdl-data-table__cell--non-numeric employer">{{ job.employer.company.company_name }}</td>
            <td class="mdl-data-table__cell--non-numeric">{{ job.get_skill_display }}</td>
            <td class="mdl-data-table__cell deadline">{{ job.deadline }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>



{% endblock %}

{% block right_content %}
  
             <!-- Right aligned menu below button -->
  Skill Level
  <button id="demo-menu-lower-right"
          class="mdl-button mdl-js-button mdl-button--icon"> 
    <i class="material-icons">more_vert</i>
  </button>

  <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect"
        for="demo-menu-lower-right">
    <a style="text-decoration: none" href="/hub/student/skill/J"><li class="mdl-menu__item">Junior</li></a>
    <a style="text-decoration: none" href="/hub/student/skill/I"><li class="mdl-menu__item">Intermediate</li></a>
    <!--<li disabled class="mdl-menu__item">Disabled Action</li> -->
    <a style="text-decoration: none" href="/hub/student/skill/S"><li class="mdl-menu__item">Senior</li></a>
  </ul>


{% endblock %}

{% block external_scripts %}
  <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0-alpha1/jquery.min.js'></script>
  <script src='https://s3-us-west-2.amazonaws.com/s.cdpn.io/4579/list.min.js'></script>
  <script src="/hub/static/js/index.js"></script>
{% endblock %}

internHub/hub/templates/hub/job.html
{% extends 'hub/base.html' %}

{% block title %}{{ job.title }}{% endblock %}

{% block other_styles %}
  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">

  <style>
  .full-width {
    width: 100%;
  }
  .backbutton {
    float: right;
    bottom: 0;
    position: fixed;
    margin-bottom: 1%;
  }
  </style>

{% endblock %}

{% block middle_content %}
  <div style="padding: 80px 56px" class="content mdl-card mdl-shadow--2dp full-width">
    <h1>{{ job.title }}</h1>
    <h2>{{ job.employer }}</h2>
    <h3>{{ job.get_skill_display }}</h3>
    <p>{{ job.description | linebreaks}}</p>
  </div>

{% endblock %}

{% block right_content %}
  <button class="mdl-button mdl-js-button mdl-js-ripple-effect" onclick="window.location.href='/hub/student/job/{{ job.id }}/apply'">Apply</button>
{% endblock %}

internHub/hub/templates/hub/job_desc.html
{% extends 'hub/base.html' %}

{% block title %}{{ job.title }}{% endblock %}

{% block other_styles %}
  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">

  <style>
  .full-width {
    width: 100%;
  }
  .backbutton {
    float: right;
    bottom: 0;
    position: fixed;
    margin-bottom: 1%;
  }
  </style>

{% endblock %}

{% block middle_content %}
  <div style="padding: 80px 56px" class="content mdl-card mdl-shadow--2dp full-width">
    <h1>{{ job.title }}</h1>
    <h2>{{ job.employer.company.company_name }}</h2>
    <h3>{{ job.get_skill_display }}</h3>
    <p>{{ job.description | linebreaks}}</p>
  </div>

{% endblock %}

internHub/hub/templates/hub/new_job.html
{% extends 'hub/base_employer.html' %}

{% block title %}New Job{% endblock %}
{% block other_styles %}
<!-- Page styles -->  
<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">


<style>
.full-width {
  width: 100%;
}
.extra-wide {
  width: 250%;
}

</style> 
{% endblock %}

{% block middle_content %}
  <div style="padding: 80px 56px" class="content mdl-card mdl-shadow--2dp full-width">
    <h1>Create a New Job</h1>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
	    <input class="mdl-textfield__input" type="text" id="id_title" name="title">
	    <label class="mdl-textfield__label" for="id_title">Title</label>
	  </div>
      <br>
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
	    <textarea class="mdl-textfield__input extra-wide" rows=15 type="text" id="id_description" name="description"></textarea>
	    <label class="mdl-textfield__label" for="id_description">Description</label>
	  </div>
      <br>
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <select class="mdl-textfield__input" id="id_skill" name="skill">
          <option></option>
          <option value="J">Junior</option>
          <option value="I">Intermediate</option>
          <option value="S">Senior</option>
        </select>
        <label class="mdl-textfield__label" for="id_skill">Skill Level</label>
      </div>
      <br>
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
	    <input class="mdl-textfield__input" type="text" id="id_deadline" name="deadline">
	    <label class="mdl-textfield__label" for="id_deadline">Deadline(YYYY-MM-DD)</label>
	  </div>
      <br>
      <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" type="submit">
      Submit
      </button>
    </form>
  </div>
{% endblock %}

internHub/hub/templates/hub/student_applications.html
{% extends 'hub/base.html' %}

{% block title %}Student{% endblock %}

{% block other_styles %}
  <link rel="stylesheet" href="/hub/static/css/style.css">

  <style>
  .full-width {
    width: 100%;
  }
  </style> 
{% endblock %}

{% block middle_content %}
  <div id="mdl-table">
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable is-upgraded is-focused">
      <label class="mdl-button mdl-js-button mdl-button--icon" for="sample6">
              <i class="material-icons">search</i>
      </label>
      <div class="mdl-textfield__expandable-holder full-width">
              <input class="mdl-textfield__input search full-width" type="text" id="sample6">
              <label class="mdl-textfield__label" for="sample-expandable">Expandable Input</label>
      </div>
    </div>
    <table id='mdl-table' class="mdl-data-table mdl-js-data-table mdl-data-table mdl-shadow--2dp full-width">
      <thead>
        <tr>
          <th class="mdl-data-table__cell--non-numeric" data-sort="jobtitle">Job Title</th>
          <th class="mdl-data-table__cell--non-numeric" data-sort="employer">Employer</th>
          <th class="mdl-data-table__cell--non-numeric">Skill Level</th>
          <th class="mdl-data-table__cell sort" data-sort="deadline">Deadline</th>
        </tr>
      </thead>
      <tbody class="list">
        {% for application in job_list %}
          <tr>
            <td class="mdl-data-table__cell--non-numeric jobtitle"><a href="/hub/student/applications/{{ application.job.id }}/">{{ application.job.title }}</td>
            <td class="mdl-data-table__cell--non-numeric employer">{{ application.job.employer }}</td>
            <td class="mdl-data-table__cell--non-numeric">{{ application.job.get_skill_display }}</td>
            <td class="mdl-data-table__cell deadline">{{ application.job.deadline }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>



{% endblock %}

{% block right_content %}
  
             <!-- Right aligned menu below button -->
  Skill Level
  <button id="demo-menu-lower-right"
          class="mdl-button mdl-js-button mdl-button--icon"> 
    <i class="material-icons">more_vert</i>
  </button>

  <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect"
        for="demo-menu-lower-right">
    <a style="text-decoration: none" href="/hub/student/skill/J"><li class="mdl-menu__item">Junior</li></a>
    <a style="text-decoration: none" href="/hub/student/skill/I"><li class="mdl-menu__item">Intermediate</li></a>
    <!--<li disabled class="mdl-menu__item">Disabled Action</li> -->
    <a style="text-decoration: none" href="/hub/student/skill/S"><li class="mdl-menu__item">Senior</li></a>
  </ul>


{% endblock %}

{% block external_scripts %}
  <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0-alpha1/jquery.min.js'></script>
  <script src='https://s3-us-west-2.amazonaws.com/s.cdpn.io/4579/list.min.js'></script>
  <script src="/hub/static/js/index.js"></script>
{% endblock %}